### ISSUE TITLE
amd64

### ISSUE THREAD

**Issue by Akior** [denzen84/sstgb#1]
Можно ли ожидать версию под amd64 и прочие ?

**Comment by denzen84** [comment]
amd64 bin release uploaded

**Comment by Akior** [comment]
С выложенным telebot.so 

sstgb: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libtelebot.so.0.4.5)

**Comment by denzen84** [comment]
sudo apt-get install libcurl4 libjson-c3
